/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 구글 로그인
         * @description Google ID Token을 서버가 로컬 검증한다(캐싱된 공개키로 JWT 서명 검증).
         *     최초 로그인 시 자동 가입하고 users.nickname을 구글 이름으로 세팅한다.
         *     isNewUser로 프론트가 온보딩(알 선택 화면 1-1)으로 분기한다.
         */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description 401 + TOKEN_EXPIRED 수신 시 프론트가 이 엔드포인트를 1회 호출하고 원 요청을 재시도한다.
         *     재차 401이면 로그인 화면으로 보낸다.
         *     refreshToken은 요청 바디로 받는다(httpOnly 쿠키 아님).
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 현재 로그인한 사용자의 프로필 정보를 반환한다.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴
         * @description soft delete + PII 익명화. email→deleted_{id}@myith.local, google_id→null, nickname→탈퇴한 사용자, profile_image_url→null.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 닉네임 또는 프로필 이미지를 변경한다. 모든 필드는 optional이다.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 직무 목록 조회
         * @description 화면 2(캐릭터 생성) 직무 카드 목록에 사용한다.
         *     available: false는 job_profile이 아직 없는 직무. 프론트가 '준비중' 잠긴 카드로 표시한다.
         *     keywords는 job_profile 분야 축 상위 5개. 프로필이 없으면 빈 배열이다(null 아님).
         */
        get: operations["getJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobCode}/diagnosis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 자가진단 문항 조회
         * @description 화면 3(자가진단) 문항 목록을 반환한다.
         *     문항 개수는 직무마다 다르다(6~10개). 배열 길이를 고정하지 않는다.
         *     levels는 4단계 고정이다. mastery는 참고용이며 프론트는 id만 서버로 보낸다.
         *     profileVersion은 프론트가 보관했다가 POST /api/roadmaps 요청에 그대로 실어 보낸다.
         */
        get: operations["getDiagnosis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobCode}/axes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 직무별 역량 축 조회
         * @description 아카이브의 역량 다각형 축과 경험 카드 역량 필터 목록에 사용한다.
         */
        get: operations["getJobAxes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * S3 Presigned URL 발급
         * @description 프론트가 uploadUrl로 S3에 직접 PUT 업로드하고, fileKey만 로드맵 생성에 넘긴다.
         *     서버는 파일 본문을 받지 않는다.
         *     허용 타입: application/pdf, image/png, image/jpeg. 상한 10MB.
         */
        post: operations["presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 캐릭터 목록 조회
         * @description 화면 1-1(알 선택, 캐릭터 없을 때)과 1-2(홈, 캐릭터 있을 때) 모두에 사용한다.
         *     프론트는 응답의 species 목록으로 알 선택 화면에서 보유 종류를 제외한다.
         *     nextQuest가 null이면 모든 퀘스트 완료 상태다.
         *     사이드바 카드와 홈 화면 카드가 함께 쓴다.
         *     status=archived로 아카이브된 로드맵을 조회한다(경험 카드 열람용).
         */
        get: operations["getCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{characterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 캐릭터 삭제
         * @description 신화 허브의 캐릭터 카드에서 삭제할 때 호출한다.
         *     캐릭터에 연결된 로드맵과 퀘스트, STAR 기록의 삭제 정책은 백엔드에서 함께 확정해야 한다.
         */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로드맵 생성
         * @description narrative·repoUrl·fileKey는 전부 optional이다.
         *     셋 중 하나라도 있으면 202(비동기 분석, generationState: ANALYZING),
         *     없으면 200(즉시 조립, generationState: READY).
         *     같은 직무의 기존 ACTIVE 로드맵이 있으면 자동으로 ARCHIVED 처리하고 새로 만든다. STAR 기록은 보존된다.
         *     검증: nickname trim 후 1~20자 / jobCode는 available: true여야 함 / 모든 필수 문항 응답 필요.
         */
        post: operations["createRoadmap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로드맵 생성 진행률 (SSE)
         * @description POST /api/roadmaps에서 202를 받은 뒤 구독한다.
         *
         *     이벤트 3종:
         *     - event: progress — data: { "step": "증거 분석", "percent": 60 }
         *     - event: done — data: { "roadmapId": "rmp_01J3ABC" }
         *     - event: error — data: { "code": "ANALYSIS_FAILED", "message": "분석에 실패했습니다." }
         *
         *     연결이 끊겨도 결과는 서버에 저장된다.
         *     재접속 시 GET /api/roadmaps/{roadmapId}로 완성본을 조회할 수 있다.
         */
        get: operations["progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로드맵 상세 조회
         * @description 화면 4-1(로드맵 상세).
         *     levels는 오름차순, quests는 order 오름차순으로 내린다.
         *     레벨 개수는 직무마다 4~7개로 다르다. 구분선에는 "Stage 1"만 표시한다.
         *     잠긴 퀘스트(LOCKED)도 목록에 포함한다.
         *     version은 낙관적 락용이다. 프론트가 보관했다가 완료·순서변경 요청에 실어 보낸다.
         */
        get: operations["getDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사용자 정의 퀘스트 추가
         * @description 화면 4-1 퀘스트 추가. source는 자동으로 CUSTOM으로 설정된다.
         */
        post: operations["addQuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/quests/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 퀘스트 순서 변경
         * @description 화면 4-1 드래그&드롭으로 퀘스트 순서를 변경한다. version은 낙관적 락용이다.
         */
        patch: operations["reorderQuest"];
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/quests/{questId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 퀘스트 삭제
         * @description source가 CUSTOM인 사용자 정의 퀘스트만 삭제할 수 있다.
         */
        delete: operations["deleteQuest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quests/{questId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 퀘스트 상세 조회
         * @description 화면 4-2(퀘스트 상세 + STAR).
         *     ncsUnit은 source: CUSTOM이면 null이다.
         *     certifications는 연계 자격 전부를 내린다. 없으면 빈 배열(프론트가 '해당 없음' 표시).
         *     star가 null이면 입력칸을 빈 값으로 시작한다.
         */
        get: operations["getQuestDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quests/{questId}/star": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * STAR 기록 저장 (임시 저장)
         * @description 각 필드 trim 후 0~2000자. 임시 저장이므로 빈 값을 허용한다.
         *     최초 저장 시 퀘스트 상태가 OPEN → PENDING으로 바뀐다.
         *     프론트는 textarea blur 또는 debounce로 호출한다.
         *     AI 제안을 적용해 저장한 경우 source: "ai-assisted" + aiEnhancementId를 채운다.
         */
        put: operations["saveStar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quests/{questId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 퀘스트 완료 토글
         * @description STAR 본문은 여기서 보내지 않는다. PUT /star로 이미 저장된 값을 쓴다.
         *     응답에 radar를 함께 내려 프론트가 레이더를 재조회 없이 갱신하게 한다.
         *     409 VERSION_CONFLICT 응답에는 최신 version을 포함해 프론트가 재시도할 수 있게 한다.
         */
        patch: operations["toggleComplete"];
        trace?: never;
    };
    "/api/quests/{questId}/ai-enhancements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * STAR AI 보완 요청
         * @description STAR 원문을 AI에게 보내 보완 제안·피드백·자기소개서 초안을 받는다.
         *     서버는 원문을 수정하지 않는다. 사용자가 '적용'을 누르면 프론트가 textarea를 채우고 PUT /star로 저장한다.
         *     202 수신 후 프론트가 GET /api/ai-enhancements/{requestId}를 짧은 간격으로 폴링한다.
         */
        post: operations["requestAiEnhancement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-enhancements/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 보완 결과 조회
         * @description POST /api/quests/{questId}/ai-enhancements에서 202 수신 후 프론트가 짧은 간격으로 폴링한다.
         *     enhancedStar → 비교 모달 오른쪽 / feedback → 항목별 힌트 / resumeDraft → 자기소개서 초안 영역.
         *     서버는 원문을 수정하지 않는다. 사용자가 '적용'을 누르면 프론트가 textarea를 채우고 PUT /star로 저장한다.
         */
        get: operations["getAiEnhancementResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 대시보드 조회
         * @description 화면 5(대시보드/신화 페이지).
         *     radar는 배열이다. 축 개수가 직무마다 다르므로 고정 키 객체로 만들지 않는다.
         *     percent는 단순 완료율 = (DONE+ALREADY_KNOWN)/전체 × 100이다. 가중평균이 아니다.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/star/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경험 카드(STAR 기록) 목록 조회
         * @description 화면 5(대시보드) 경험 카드 목록. 커서 기반 페이지네이션(OFFSET 금지).
         */
        get: operations["getRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmaps/{roadmapId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로드맵 내보내기
         * @description format=md: 자소서 생성용 프롬프트 문서 (Content-Type: text/markdown; charset=utf-8).
         *     format=pdf: 원본 STAR 열람용 PDF (Content-Type: application/pdf, 한글 폰트 임베딩).
         *     대상: 해당 로드맵의 star IS NOT NULL인 경험 카드 전체(완성도 무관).
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 하트비트
         * @description Electron 상주 앱 전용이다. 웹 프론트는 호출하지 않는다.
         *     서버는 마지막 실제 서비스 활동 시각 기준으로 48시간 미접속을 판정해 nudge: true로 응답한다.
         *     heartbeat 자체는 활동 시각을 갱신하지 않는다(갱신하면 48시간이 영원히 지나지 않는다).
         *     캐릭터가 없으면 characterState: null.
         */
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 헬스체크
         * @description 서버 상태를 확인한다.
         *     이 엔드포인트는 data 래퍼를 사용하지 않는 유일한 엔드포인트다.
         *     모니터링 도구(AWS ALB, k8s probe 등) 호환을 위해 래퍼 없이 평문 JSON을 반환한다.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        QuestStatus: "LOCKED" | "OPEN" | "PENDING" | "DONE" | "ALREADY_KNOWN";
        /** @enum {string} */
        QuestSource: "SKILL" | "ACTIVITY" | "CUSTOM";
        /** @enum {string} */
        StarSource: "manual" | "ai-assisted";
        /** @enum {string} */
        GenerationState: "PENDING" | "ANALYZING" | "READY" | "FAILED";
        /** @enum {string} */
        RoadmapStatus: "ACTIVE" | "ARCHIVED";
        /** @enum {string} */
        ExportFormat: "md" | "pdf";
        /** @enum {string} */
        AiRequestStatus: "PROCESSING" | "COMPLETED" | "FAILED";
        ErrorResponse: {
            error?: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @example QUEST_LOCKED */
            code?: string;
            /** @example 선행 퀘스트를 먼저 완료해주세요. */
            message?: string;
            fieldErrors?: {
                [key: string]: string;
            } | null;
            /** @example req_01J3ABC */
            requestId?: string;
        };
        Meta: {
            nextCursor?: string | null;
            hasNext?: boolean;
            retryAfterSeconds?: number | null;
        };
        AxisItem: {
            /** @description 역량 축 코드. enum이 아닌 자유 문자열 */
            axisCode: string;
            axisName: string;
            /** @description 단순 완료율 = (DONE+ALREADY_KNOWN)/전체 × 100 */
            percent: number;
        };
        StarInput: {
            situation?: string;
            task?: string;
            action?: string;
            result?: string;
        };
        NextQuest: {
            questId?: string;
            title?: string;
        } | null;
        QuestItem: {
            questId: string;
            title: string;
            axisCode: string;
            axisName: string;
            /** @description 화면 4-1 카드 상태(잠금 자물쇠/완료/이미보유 뱃지) */
            status: components["schemas"]["QuestStatus"];
            source: components["schemas"]["QuestSource"];
            order: number;
            /** Format: int64 */
            version: number;
            level?: number;
        };
        LevelGroup: {
            level: number;
            quests: components["schemas"]["QuestItem"][];
        };
        NcsUnit: {
            code?: string;
            name?: string;
            description?: string;
        } | null;
        CertItem: {
            name?: string;
        };
        FeedbackEntry: {
            /** @enum {string} */
            field?: "situation" | "task" | "action" | "result";
            issue?: string;
            suggestion?: string;
        };
        ExperienceCard: {
            experienceId?: string;
            questId?: string;
            title?: string;
            axisCode?: string;
            axisName?: string;
            ncsUnitName?: string | null;
            star?: components["schemas"]["StarInput"];
            /** Format: date-time */
            createdAt?: string;
        };
        GoogleLoginRequest: {
            idToken: string;
        };
        GoogleLoginResponse: {
            accessToken?: string;
            refreshToken?: string;
            isNewUser?: boolean;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponse: {
            accessToken?: string;
        };
        UserResponse: {
            id?: string;
            email?: string;
            nickname?: string;
            profileImageUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateMeRequest: {
            nickname?: string;
            profileImageUrl?: string | null;
        };
        PresignRequest: {
            fileName: string;
            contentType: string;
        };
        PresignResponse: {
            uploadUrl?: string;
            fileKey?: string;
            expiresIn?: number;
        };
        JobListResponse: {
            categories?: components["schemas"]["Category"][];
        };
        Category: {
            categoryCode?: string;
            categoryName?: string;
            sortOrder?: number;
            jobs?: components["schemas"]["JobItem"][];
        };
        JobItem: {
            /** @description 직무 코드. enum이 아닌 자유 문자열 */
            jobCode?: string;
            jobName?: string;
            /** @description 화면 2 직무 카드 설명문, 로드맵 상세 상단 */
            tagline?: string;
            /** @description 화면 2 직무 카드 하단 키워드 5개. 프로필 없으면 빈 배열 */
            keywords?: string[];
            /** @description false면 화면 2에서 '준비중' 잠긴 카드 */
            available?: boolean;
        };
        JobAxesResponse: {
            jobCode: string;
            axes: components["schemas"]["JobAxis"][];
        };
        JobAxis: {
            axisCode: string;
            axisName: string;
        };
        DiagnosisResponse: {
            jobCode?: string;
            profileVersion?: number;
            questions?: components["schemas"]["DiagnosisQuestion"][];
            levels?: components["schemas"]["DiagnosisLevel"][];
        };
        DiagnosisQuestion: {
            skillCode?: string;
            text?: string;
            axisCode?: string;
            axisName?: string;
            sortOrder?: number;
        };
        DiagnosisLevel: {
            /** @enum {string} */
            id?: "unknown" | "heard" | "tried" | "independent";
            label?: string;
            mastery?: number;
        };
        CharacterSummary: {
            characterId?: string;
            roadmapId?: string;
            /** @description 캐릭터 종류. enum이 아닌 자유 문자열. 이미지 파일명 {species}-{stage}.png에 사용 */
            species?: string;
            /** @description 홈 화면(1-2) 카드 큰 제목, 사이드바 첫 줄 */
            nickname?: string;
            /** @description 직무 코드. enum이 아닌 자유 문자열 */
            jobCode?: string;
            /** @description 홈 화면 카드 작은 글씨, 로드맵 상세 상단 */
            jobName?: string;
            tagline?: string;
            roadmapStatus?: components["schemas"]["RoadmapStatus"];
            completionRate?: number;
            stage?: number;
            /** @enum {string} */
            stageLabel?: "시작" | "성장" | "숙련" | "완성";
            level?: number;
            nextQuest?: components["schemas"]["NextQuest"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateRoadmapRequest: {
            jobCode: string;
            profileVersion: number;
            species: string;
            nickname?: string;
            answers: components["schemas"]["AnswerRequest"][];
            narrative?: components["schemas"]["NarrativeRequest"];
            /**
             * @description GitHub 저장소 URL (optional)
             * @example https://github.com/user/community
             */
            repoUrl?: string;
            /**
             * @description POST /api/uploads/presign에서 받은 파일 키 (optional)
             * @example portfolio/usr_01J3ABC/9f2c1d.pdf
             */
            fileKey?: string;
        };
        AnswerRequest: {
            skillCode: string;
            /** @enum {string} */
            level: "unknown" | "heard" | "tried" | "independent";
        };
        NarrativeRequest: {
            /**
             * @description 경험 서술
             * @example 스프링으로 커뮤니티 CRUD를 만들어봤습니다.
             */
            experience?: string;
            /**
             * @description 강점 서술
             * @example Java와 Spring이 가장 익숙합니다.
             */
            strength?: string;
            /**
             * @description 어려움 서술
             * @example 성능 최적화는 아직 해본 적이 없습니다.
             */
            difficulty?: string;
        };
        CreateRoadmapResponse: {
            roadmapId?: string;
            generationState?: components["schemas"]["GenerationState"];
        };
        RoadmapDetail: {
            roadmapId?: string;
            generationState?: components["schemas"]["GenerationState"];
            roadmapStatus?: components["schemas"]["RoadmapStatus"];
            jobCode?: string;
            jobName?: string;
            tagline?: string;
            character?: components["schemas"]["RoadmapCharacter"];
            levels?: components["schemas"]["LevelGroup"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        RoadmapCharacter: {
            characterId?: string;
            species?: string;
            nickname?: string;
            /** @description 캐릭터 이미지 파일명 숫자. {species}-{stage}.png */
            stage?: number;
            /**
             * @description 캐릭터 옆 텍스트 (시작/성장/숙련/완성)
             * @enum {string}
             */
            stageLabel?: "시작" | "성장" | "숙련" | "완성";
            completionRate?: number;
        };
        AddQuestRequest: {
            title: string;
            axisCode: string;
            level: number;
        };
        ReorderRequest: {
            /**
             * @description 이동할 퀘스트 ID
             * @example qst_02
             */
            questId: string;
            targetLevel: number;
            targetIndex: number;
            /** Format: int64 */
            version: number;
        };
        QuestDetail: {
            questId?: string;
            roadmapId?: string;
            level?: number;
            axisCode?: string;
            axisName?: string;
            title?: string;
            status?: components["schemas"]["QuestStatus"];
            source?: components["schemas"]["QuestSource"];
            order?: number;
            /** Format: int64 */
            version?: number;
            /** @description 화면 4-2 '완료 기준' 박스 */
            completionCriteria?: string | null;
            /** @description 화면 4-2 'NCS 능력단위 근거' 박스. null이면 섹션 숨김 */
            ncsUnit?: components["schemas"]["NcsUnit"];
            /** @description 화면 4-2 '추천 자격'. 빈 배열이면 '해당 없음' */
            certifications?: components["schemas"]["CertItem"][];
            /** @description 화면 4-2 STAR 입력칸 초기값. 아직 작성 전이면 null */
            star?: components["schemas"]["StarInput"] | null;
            starSource?: components["schemas"]["StarSource"] | null;
            /** Format: date-time */
            updatedAt?: string;
        };
        SaveStarRequest: {
            star?: components["schemas"]["StarInput"];
            source?: components["schemas"]["StarSource"];
            aiEnhancementId?: string | null;
        };
        SaveStarResponse: {
            questId?: string;
            star?: components["schemas"]["StarInput"];
            source?: components["schemas"]["StarSource"];
            status?: components["schemas"]["QuestStatus"];
            /** Format: date-time */
            updatedAt?: string;
        };
        CompleteRequest: {
            completed: boolean;
            /** Format: int64 */
            version: number;
        };
        CompleteResponse: {
            quest?: {
                questId?: string;
                status?: components["schemas"]["QuestStatus"];
                /** Format: date-time */
                completedAt?: string;
                /** Format: int64 */
                version?: number;
            };
            characterChanges?: {
                completionRate?: number;
                stage?: number;
                /** @enum {string} */
                stageLabel?: "시작" | "성장" | "숙련" | "완성";
                level?: number;
                nextQuest?: components["schemas"]["NextQuest"];
            };
            unlockedQuestIds?: string[];
            radar?: components["schemas"]["AxisItem"][];
        };
        AiEnhancementRequest: {
            star?: components["schemas"]["StarInput"];
            locale?: string;
            style?: string;
        };
        AiEnhancementResult: {
            requestId: string;
            questId?: string | null;
            status: components["schemas"]["AiRequestStatus"];
            /** @description 화면 4-2 AI 비교 모달 오른쪽. status가 PROCESSING이면 아직 없음 */
            enhancedStar?: components["schemas"]["StarInput"] | null;
            /** @description 화면 4-2 항목별 개선 힌트 */
            feedback?: components["schemas"]["FeedbackEntry"][] | null;
            /** @description 화면 4-2·5 자기소개서 초안 영역 */
            resumeDraft?: string | null;
            errorCode?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
        };
        DashboardResponse: {
            character?: components["schemas"]["DashboardCharacter"];
            /** @description 화면 5 역량 다각형(레이더). 축 개수는 직무마다 4~7개 가변 */
            radar?: components["schemas"]["AxisItem"][];
            skillTree?: components["schemas"]["SkillTreeLevel"][];
            /** @description 화면 5 경험 카드 목록 */
            experienceCards?: components["schemas"]["ExperienceCard"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        DashboardCharacter: {
            nickname?: string;
            jobName?: string;
            species?: string;
            stage?: number;
            /** @enum {string} */
            stageLabel?: "시작" | "성장" | "숙련" | "완성";
            completionRate?: number;
            completedQuestCount?: number;
            level?: number;
        };
        SkillTreeLevel: {
            level?: number;
            quests?: {
                questId?: string;
                title?: string;
                axisCode?: string;
                axisName?: string;
                status?: components["schemas"]["QuestStatus"];
            }[];
        };
        HeartbeatResponse: {
            nudge?: boolean;
            characterState?: {
                species?: string;
                stage?: number;
                completionRate?: number;
            } | null;
        };
        HealthResponse: {
            status?: string;
            version?: string;
            /** Format: date-time */
            time?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3JfMDFKM0FCQyJ9.abc",
                     *         "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3JfMDFKM0FCQyJ9.xyz",
                     *         "isNewUser": true
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["GoogleLoginResponse"];
                    };
                };
            };
            /** @description INVALID_ID_TOKEN — Google ID Token 검증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_ID_TOKEN",
                     *         "message": "Google ID Token 검증에 실패했습니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c3JfMDFKM0FCQyJ9.new"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["RefreshResponse"];
                    };
                };
            };
            /** @description INVALID_REFRESH_TOKEN — refreshToken 무효 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_REFRESH_TOKEN",
                     *         "message": "유효하지 않은 토큰입니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": "usr_01J3ABC",
                     *         "email": "sungyoon@example.com",
                     *         "nickname": "이성윤",
                     *         "profileImageUrl": null,
                     *         "createdAt": "2026-07-01T00:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["UserResponse"];
                    };
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 탈퇴 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "id": "usr_01J3ABC",
                     *         "email": "sungyoon@example.com",
                     *         "nickname": "새이름",
                     *         "profileImageUrl": null,
                     *         "createdAt": "2026-07-01T00:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["UserResponse"];
                    };
                };
            };
            /** @description VALIDATION_ERROR — nickname trim 후 1~20자 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "VALIDATION_ERROR",
                     *         "message": "입력값이 올바르지 않습니다.",
                     *         "fieldErrors": {
                     *           "nickname": "닉네임은 1~20자여야 합니다."
                     *         },
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "categories": [
                     *           {
                     *             "categoryCode": "it",
                     *             "categoryName": "IT·개발",
                     *             "sortOrder": 1,
                     *             "jobs": [
                     *               {
                     *                 "jobCode": "server",
                     *                 "jobName": "백엔드 개발자",
                     *                 "tagline": "서버와 데이터베이스를 설계하고, 안정적으로 동작하는 API를 구현합니다.",
                     *                 "keywords": [
                     *                   "프로그래밍 기초",
                     *                   "CS·자료구조",
                     *                   "데이터입출력",
                     *                   "서버·API",
                     *                   "협업·형상관리"
                     *                 ],
                     *                 "available": true
                     *               },
                     *               {
                     *                 "jobCode": "android",
                     *                 "jobName": "안드로이드 개발자",
                     *                 "tagline": "안드로이드 환경에서 동작하는 애플리케이션을 구현합니다.",
                     *                 "keywords": [],
                     *                 "available": false
                     *               }
                     *             ]
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["JobListResponse"];
                    };
                };
            };
        };
    };
    getDiagnosis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "jobCode": "server",
                     *         "profileVersion": 1,
                     *         "questions": [
                     *           {
                     *             "skillCode": "lang-basic",
                     *             "text": "프로그래밍 언어 기초를 이해한다",
                     *             "axisCode": "programming",
                     *             "axisName": "프로그래밍 기초",
                     *             "sortOrder": 1
                     *           },
                     *           {
                     *             "skillCode": "data-structure",
                     *             "text": "자료구조를 활용한다",
                     *             "axisCode": "cs",
                     *             "axisName": "CS·자료구조",
                     *             "sortOrder": 2
                     *           },
                     *           {
                     *             "skillCode": "sql",
                     *             "text": "SQL로 데이터를 다룬다",
                     *             "axisCode": "database",
                     *             "axisName": "데이터입출력",
                     *             "sortOrder": 3
                     *           },
                     *           {
                     *             "skillCode": "rest",
                     *             "text": "REST API 서버를 구현한다",
                     *             "axisCode": "server-api",
                     *             "axisName": "서버·API",
                     *             "sortOrder": 4
                     *           },
                     *           {
                     *             "skillCode": "git",
                     *             "text": "버전관리로 협업한다",
                     *             "axisCode": "collaboration",
                     *             "axisName": "협업·형상관리",
                     *             "sortOrder": 5
                     *           },
                     *           {
                     *             "skillCode": "deploy",
                     *             "text": "애플리케이션을 배포한다",
                     *             "axisCode": "deploy",
                     *             "axisName": "배포·운영",
                     *             "sortOrder": 6
                     *           }
                     *         ],
                     *         "levels": [
                     *           {
                     *             "id": "unknown",
                     *             "label": "모름",
                     *             "mastery": 0
                     *           },
                     *           {
                     *             "id": "heard",
                     *             "label": "들어봄",
                     *             "mastery": 0.33
                     *           },
                     *           {
                     *             "id": "tried",
                     *             "label": "해봄",
                     *             "mastery": 0.66
                     *           },
                     *           {
                     *             "id": "independent",
                     *             "label": "혼자 가능",
                     *             "mastery": 1
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["DiagnosisResponse"];
                    };
                };
            };
            /** @description JOB_PROFILE_NOT_READY — 해당 직무의 job_profile 미생성 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "JOB_PROFILE_NOT_READY",
                     *         "message": "해당 직무의 프로필이 아직 준비되지 않았습니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobAxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 직무 코드
                 * @example server
                 */
                jobCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "jobCode": "backend",
                     *         "axes": [
                     *           {
                     *             "axisCode": "programming",
                     *             "axisName": "프로그래밍기초"
                     *           },
                     *           {
                     *             "axisCode": "cs",
                     *             "axisName": "CS·자료구조"
                     *           },
                     *           {
                     *             "axisCode": "data-io",
                     *             "axisName": "데이터입출력"
                     *           },
                     *           {
                     *             "axisCode": "server-api",
                     *             "axisName": "서버·API"
                     *           },
                     *           {
                     *             "axisCode": "collab",
                     *             "axisName": "협업·형상관리"
                     *           },
                     *           {
                     *             "axisCode": "devops",
                     *             "axisName": "배포·운영"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["JobAxesResponse"];
                    };
                };
            };
        };
    };
    presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description 발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "uploadUrl": "https://myith-uploads.s3.ap-northeast-2.amazonaws.com/...",
                     *         "fileKey": "portfolio/usr_01J3ABC/9f2c1d.pdf",
                     *         "expiresIn": 900
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["PresignResponse"];
                    };
                };
            };
            /** @description UNSUPPORTED_FILE_TYPE / FILE_TOO_LARGE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNSUPPORTED_FILE_TYPE",
                     *         "message": "허용되지 않는 파일 형식입니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCharacters: {
        parameters: {
            query?: {
                /**
                 * @description active | archived | all (기본 active)
                 * @example active
                 */
                status?: "active" | "archived" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "characterId": "chr_01J3ABC",
                     *           "roadmapId": "rmp_01J3ABC",
                     *           "species": "deokbaseu",
                     *           "nickname": "견습 서버 개발자",
                     *           "jobCode": "server",
                     *           "jobName": "백엔드 개발자",
                     *           "tagline": "서버와 데이터베이스를 설계하고, 안정적으로 동작하는 API를 구현합니다.",
                     *           "roadmapStatus": "ACTIVE",
                     *           "completionRate": 80,
                     *           "stage": 4,
                     *           "stageLabel": "완성",
                     *           "level": 4,
                     *           "nextQuest": {
                     *             "questId": "qst_01J3ABC",
                     *             "title": "REST API 서버를 구현한다"
                     *           },
                     *           "createdAt": "2026-07-20T02:00:00Z",
                     *           "updatedAt": "2026-07-24T03:00:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["CharacterSummary"][];
                    };
                };
            };
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 삭제할 캐릭터 ID
                 * @example chr_01J3ABC
                 */
                characterId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CHARACTER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "CHARACTER_NOT_FOUND",
                     *         "message": "캐릭터를 찾을 수 없습니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRoadmap: {
        parameters: {
            query?: never;
            header?: {
                /** @description 멱등성 키 (optional) */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoadmapRequest"];
            };
        };
        responses: {
            /** @description 즉시 조립 완료 (선택형만) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CreateRoadmapResponse"];
                    };
                };
            };
            /** @description 비동기 분석 접수 (서술형·repo·파일) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["CreateRoadmapResponse"];
                    };
                };
            };
            /** @description VALIDATION_ERROR */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "VALIDATION_ERROR",
                     *         "message": "입력값이 올바르지 않습니다.",
                     *         "fieldErrors": {
                     *           "nickname": "닉네임은 1~20자여야 합니다."
                     *         },
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    progress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 스트림 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "roadmapId": "rmp_01J3ABC",
                     *         "generationState": "READY",
                     *         "roadmapStatus": "ACTIVE",
                     *         "jobCode": "server",
                     *         "jobName": "백엔드 개발자",
                     *         "tagline": "서버와 데이터베이스를 설계하고, 안정적으로 동작하는 API를 구현합니다.",
                     *         "character": {
                     *           "characterId": "chr_01J3ABC",
                     *           "species": "deokbaseu",
                     *           "nickname": "견습 서버 개발자",
                     *           "stage": 4,
                     *           "stageLabel": "완성",
                     *           "completionRate": 80
                     *         },
                     *         "levels": [
                     *           {
                     *             "level": 1,
                     *             "quests": [
                     *               {
                     *                 "questId": "qst_01",
                     *                 "title": "버전관리로 협업한다",
                     *                 "axisCode": "collaboration",
                     *                 "axisName": "협업·형상관리",
                     *                 "status": "DONE",
                     *                 "source": "SKILL",
                     *                 "order": 1,
                     *                 "version": 3
                     *               },
                     *               {
                     *                 "questId": "qst_02",
                     *                 "title": "언어 기초로 토이앱을 만든다",
                     *                 "axisCode": "programming",
                     *                 "axisName": "프로그래밍 기초",
                     *                 "status": "ALREADY_KNOWN",
                     *                 "source": "SKILL",
                     *                 "order": 2,
                     *                 "version": 1
                     *               }
                     *             ]
                     *           },
                     *           {
                     *             "level": 2,
                     *             "quests": [
                     *               {
                     *                 "questId": "qst_03",
                     *                 "title": "데이터베이스를 설계한다",
                     *                 "axisCode": "database",
                     *                 "axisName": "데이터입출력",
                     *                 "status": "LOCKED",
                     *                 "source": "SKILL",
                     *                 "order": 1,
                     *                 "version": 0
                     *               }
                     *             ]
                     *           }
                     *         ],
                     *         "updatedAt": "2026-07-24T03:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["RoadmapDetail"];
                    };
                };
            };
        };
    };
    addQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddQuestRequest"];
            };
        };
        responses: {
            /** @description 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "questId": "qst_99",
                     *         "title": "사이드 프로젝트를 운영한다",
                     *         "axisCode": "server-api",
                     *         "axisName": "서버·API",
                     *         "level": 3,
                     *         "status": "OPEN",
                     *         "source": "CUSTOM",
                     *         "order": 4,
                     *         "version": 0
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["QuestItem"];
                    };
                };
            };
            /** @description VALIDATION_ERROR — title 1~80자, level은 해당 로드맵의 레벨 범위 내 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "VALIDATION_ERROR",
                     *         "message": "입력값이 올바르지 않습니다.",
                     *         "fieldErrors": {
                     *           "title": "제목은 1~80자여야 합니다."
                     *         },
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reorderQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description 변경 성공. 갱신된 전체 레벨·퀘스트 목록 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "levels": [
                     *           {
                     *             "level": 1,
                     *             "quests": [
                     *               {
                     *                 "questId": "qst_02",
                     *                 "title": "언어 기초로 토이앱을 만든다",
                     *                 "axisCode": "programming",
                     *                 "axisName": "프로그래밍 기초",
                     *                 "status": "ALREADY_KNOWN",
                     *                 "source": "SKILL",
                     *                 "order": 1,
                     *                 "version": 1
                     *               },
                     *               {
                     *                 "questId": "qst_01",
                     *                 "title": "버전관리로 협업한다",
                     *                 "axisCode": "collaboration",
                     *                 "axisName": "협업·형상관리",
                     *                 "status": "DONE",
                     *                 "source": "SKILL",
                     *                 "order": 2,
                     *                 "version": 3
                     *               }
                     *             ]
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: {
                            levels?: components["schemas"]["LevelGroup"][];
                        };
                    };
                };
            };
            /** @description VERSION_CONFLICT — 낙관적 락 실패 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "VERSION_CONFLICT",
                     *         "message": "다른 요청과 충돌했습니다. 새로고침 후 다시 시도해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
                /** @example qst_99 */
                questId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CUSTOM_QUEST_ONLY — 사용자 정의 퀘스트가 아닌데 삭제 시도 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "CUSTOM_QUEST_ONLY",
                     *         "message": "사용자 정의 퀘스트만 삭제할 수 있습니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getQuestDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example qst_05 */
                questId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "questId": "qst_05",
                     *         "roadmapId": "rmp_01J3ABC",
                     *         "level": 5,
                     *         "axisCode": "cs",
                     *         "axisName": "CS·자료구조",
                     *         "title": "CS 면접 질문을 정리한다",
                     *         "status": "OPEN",
                     *         "source": "ACTIVITY",
                     *         "order": 1,
                     *         "version": 0,
                     *         "completionCriteria": "네트워크·OS·DB 핵심 답안을 정리한다",
                     *         "ncsUnit": {
                     *           "code": "2001010701_16v3",
                     *           "name": "응용SW기초기술활용",
                     *           "description": "자료구조와 알고리즘 등 기초 기술을 활용하는 능력"
                     *         },
                     *         "certifications": [
                     *           {
                     *             "name": "정보처리기사"
                     *           }
                     *         ],
                     *         "star": null,
                     *         "starSource": null,
                     *         "updatedAt": "2026-07-24T03:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["QuestDetail"];
                    };
                };
            };
        };
    };
    saveStar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example qst_05 */
                questId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveStarRequest"];
            };
        };
        responses: {
            /** @description 저장 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "questId": "qst_05",
                     *         "star": {
                     *           "situation": "팀 프로젝트에서 API 응답이 3초 이상 걸리는 문제가 발생했다.",
                     *           "task": "응답 시간을 500ms 이하로 줄여야 했다.",
                     *           "action": "N+1 쿼리를 페치 조인으로 개선하고 Redis 캐시를 도입했다.",
                     *           "result": "평균 응답 시간이 200ms로 감소했다."
                     *         },
                     *         "source": "manual",
                     *         "status": "PENDING",
                     *         "updatedAt": "2026-07-24T03:10:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["SaveStarResponse"];
                    };
                };
            };
            /** @description QUEST_LOCKED — 잠긴 퀘스트에 쓰기 시도 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "QUEST_LOCKED",
                     *         "message": "선행 퀘스트를 먼저 완료해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    toggleComplete: {
        parameters: {
            query?: never;
            header?: {
                /** @description 멱등성 키 (optional) */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @example qst_05 */
                questId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description 완료 처리 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "quest": {
                     *           "questId": "qst_05",
                     *           "status": "DONE",
                     *           "completedAt": "2026-07-24T03:20:00Z",
                     *           "version": 4
                     *         },
                     *         "characterChanges": {
                     *           "completionRate": 84,
                     *           "stage": 4,
                     *           "stageLabel": "완성",
                     *           "level": 5,
                     *           "nextQuest": {
                     *             "questId": "qst_06",
                     *             "title": "테스트 코드를 작성한다"
                     *           }
                     *         },
                     *         "unlockedQuestIds": [
                     *           "qst_07"
                     *         ],
                     *         "radar": [
                     *           {
                     *             "axisCode": "programming",
                     *             "axisName": "프로그래밍 기초",
                     *             "percent": 72
                     *           },
                     *           {
                     *             "axisCode": "cs",
                     *             "axisName": "CS·자료구조",
                     *             "percent": 80
                     *           },
                     *           {
                     *             "axisCode": "database",
                     *             "axisName": "데이터입출력",
                     *             "percent": 18
                     *           },
                     *           {
                     *             "axisCode": "server-api",
                     *             "axisName": "서버·API",
                     *             "percent": 67
                     *           },
                     *           {
                     *             "axisCode": "collaboration",
                     *             "axisName": "협업·형상관리",
                     *             "percent": 90
                     *           },
                     *           {
                     *             "axisCode": "deploy",
                     *             "axisName": "배포·운영",
                     *             "percent": 10
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["CompleteResponse"];
                    };
                };
            };
            /** @description VERSION_CONFLICT / QUEST_LOCKED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requestAiEnhancement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example qst_05 */
                questId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiEnhancementRequest"];
            };
        };
        responses: {
            /** @description 비동기 접수 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "requestId": "aie_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: {
                            requestId?: string;
                        };
                    };
                };
            };
            /** @description QUEST_LOCKED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "QUEST_LOCKED",
                     *         "message": "선행 퀘스트를 먼저 완료해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI_INPUT_TOO_LONG / AI_SAFETY_REJECTED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "AI_INPUT_TOO_LONG",
                     *         "message": "입력이 너무 깁니다. 각 항목을 2000자 이내로 작성해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI_RATE_LIMITED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "AI_RATE_LIMITED",
                     *         "message": "AI 요청 한도를 초과했습니다. 잠시 후 다시 시도해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAiEnhancementResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 상태에 따라 PROCESSING / COMPLETED / FAILED */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AiEnhancementResult"];
                    };
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "character": {
                     *           "nickname": "견습 서버 개발자",
                     *           "jobName": "백엔드 개발자",
                     *           "species": "deokbaseu",
                     *           "stage": 4,
                     *           "stageLabel": "완성",
                     *           "completionRate": 80,
                     *           "completedQuestCount": 7,
                     *           "level": 4
                     *         },
                     *         "radar": [
                     *           {
                     *             "axisCode": "programming",
                     *             "axisName": "프로그래밍 기초",
                     *             "percent": 67
                     *           },
                     *           {
                     *             "axisCode": "cs",
                     *             "axisName": "CS·자료구조",
                     *             "percent": 80
                     *           },
                     *           {
                     *             "axisCode": "database",
                     *             "axisName": "데이터입출력",
                     *             "percent": 18
                     *           },
                     *           {
                     *             "axisCode": "server-api",
                     *             "axisName": "서버·API",
                     *             "percent": 67
                     *           },
                     *           {
                     *             "axisCode": "collaboration",
                     *             "axisName": "협업·형상관리",
                     *             "percent": 90
                     *           },
                     *           {
                     *             "axisCode": "deploy",
                     *             "axisName": "배포·운영",
                     *             "percent": 10
                     *           }
                     *         ],
                     *         "skillTree": [
                     *           {
                     *             "level": 1,
                     *             "quests": [
                     *               {
                     *                 "questId": "qst_01",
                     *                 "title": "버전관리로 협업한다",
                     *                 "axisCode": "collaboration",
                     *                 "axisName": "협업·형상관리",
                     *                 "status": "DONE"
                     *               }
                     *             ]
                     *           }
                     *         ],
                     *         "experienceCards": [
                     *           {
                     *             "experienceId": "exp_01",
                     *             "questId": "qst_02",
                     *             "title": "언어 기초로 토이앱을 만든다",
                     *             "axisCode": "programming",
                     *             "axisName": "프로그래밍 기초",
                     *             "ncsUnitName": "프로그래밍언어활용",
                     *             "star": {
                     *               "situation": "팀 프로젝트에서 API 응답이 3초 이상 걸리는 문제가 발생했다.",
                     *               "task": "응답 시간을 500ms 이하로 줄여야 했다.",
                     *               "action": "N+1 쿼리를 페치 조인으로 개선하고 Redis 캐시를 도입했다.",
                     *               "result": "평균 응답 시간이 200ms로 감소했다."
                     *             },
                     *             "createdAt": "2026-07-22T05:00:00Z"
                     *           }
                     *         ],
                     *         "updatedAt": "2026-07-24T03:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["DashboardResponse"];
                    };
                };
            };
        };
    };
    getRecords: {
        parameters: {
            query?: {
                /**
                 * @description 커서
                 * @example eyJpZCI6ImV4cF8wMSJ9
                 */
                cursor?: string;
                /**
                 * @description 페이지 크기. 기본 20, 최대 100
                 * @example 20
                 */
                size?: number;
                /**
                 * @description 축 코드로 필터. 생략 시 전체
                 * @example programming
                 */
                axis?: string;
                /** @description 완성도 필터. all | complete | partial (기본 all). complete = STAR 4칸 모두 채워짐 */
                completeness?: "all" | "complete" | "partial";
                /**
                 * @description star_record.tags 배열 필터
                 * @example 리더십
                 */
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "experienceId": "exp_01",
                     *           "questId": "qst_02",
                     *           "title": "언어 기초로 토이앱을 만든다",
                     *           "axisCode": "programming",
                     *           "axisName": "프로그래밍 기초",
                     *           "ncsUnitName": "프로그래밍언어활용",
                     *           "star": {
                     *             "situation": "팀 프로젝트에서 API 응답이 3초 이상 걸리는 문제가 발생했다.",
                     *             "task": "응답 시간을 500ms 이하로 줄여야 했다.",
                     *             "action": "N+1 쿼리를 페치 조인으로 개선하고 Redis 캐시를 도입했다.",
                     *             "result": "평균 응답 시간이 200ms로 감소했다."
                     *           },
                     *           "createdAt": "2026-07-22T05:00:00Z"
                     *         }
                     *       ],
                     *       "meta": {
                     *         "nextCursor": "eyJpZCI6ImV4cF8wMSJ9",
                     *         "hasNext": true
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["ExperienceCard"][];
                        meta?: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /** @description 내보내기 형식. md(자소서 프롬프트) 또는 pdf(원본 STAR) */
                format?: "md" | "pdf";
            };
            header?: never;
            path: {
                /** @example rmp_01J3ABC */
                roadmapId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 다운로드 */
            200: {
                headers: {
                    /** @description 파일명. UTF-8 인코딩 */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "application/pdf": string;
                };
            };
            /** @description INVALID_EXPORT_FORMAT — format이 md/pdf가 아님 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_EXPORT_FORMAT",
                     *         "message": "지원하지 않는 내보내기 형식입니다. md 또는 pdf만 가능합니다.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NO_EXPORTABLE_EXPERIENCE — 내보낼 STAR 기록이 없음 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "NO_EXPORTABLE_EXPERIENCE",
                     *         "message": "내보낼 경험 기록이 없습니다. STAR를 먼저 작성해주세요.",
                     *         "requestId": "req_01J3ABC"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 응답 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": {
                     *         "nudge": true,
                     *         "characterState": {
                     *           "species": "deokbaseu",
                     *           "stage": 4,
                     *           "completionRate": 80
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": {
                        data?: components["schemas"]["HeartbeatResponse"];
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 서버 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0",
                     *       "time": "2026-07-24T03:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
